### ISSUE TITLE
公式字段，data_type为boolean类型时，不支持IF()和CASE()函数

### ISSUE THREAD

**Issue by TroySu** [steedos/steedos-platform#1039]
```
is_mobile:
    label: 移动位置
    type: formula
    data_type: boolean
    formula: "IF(location_type = 'Van', true, false)"
```
- Error: Incorrect parameter type for function 'IF()'. Expected Text, Number, Date, Datetime, received Checkbox

- Error: Incorrect parameter type for function 'CASE()'. Expected Text, Number, Picklist, Date, Datetime, received Checkbox
