### ISSUE TITLE
Help with Phone Number format error

### ISSUE THREAD

**Issue by sasdino** [steedos/steedos-platform#1226]
I just installed steedos platform and running the steedos server.
I want to change the language to English.
Since the cell phone filed is mandatory before saving the settings, what is phone number format that I have to type in cell phone field? It keep saying "Phone Number format error".
I've tried many phone number format, but no luck.

**Comment by sasdino** [comment]
I've figure it out, mobile phone field only accept 11 characters.
How to make change to those validation to accept more than 11 characters?

**Comment by yinlianghui** [comment]
You can fix this problem by adding an associated property to a configuration file named `steedos-config.yml` to specify the phone number format.

```
accounts:
  mobile_phone_locales: ['en-US'] 
```
You can replace the `en-US` as you want or add some more locales, see https://www.npmjs.com/package/validator for more info.

OR

```
accounts:
  mobile_regexp: '^[0-9]{10}$'
```

You can replace the `^[0-9]{10}$` with RegExp as you want.

It's important to note that if you use both `mobile_phone_locales` and `mobile_regexp`, the `mobile_phone_locales` value will take precedence

And the whole content of it may be like this:

```
datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
    appFiles:
      - "./src/**"
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"
plugins:
  - "@steedos/accounts"
tenant:
  _id:
  name: Steedos
  logo_url:
  background_url:
  saas: false
  enable_register: true
  enable_create_tenant: true
  enable_password_login: true
  enable_bind_email: false
  enable_bind_mobile: false
  enable_mobile_code_login: false
  enable_email_code_login: false
accounts:
  mobile_phone_locales: ['en-US']
```


Thank you for taking time to try out our Steedos Platform.
The instructions for using `steedos-config.yml` are not documented  yet, and we will be working on them as soon as possible. You can see it at www.steedos.org in the near future.
