### ISSUE TITLE
新标准国际化文件：.objectTranslation.yml .translation.yml 按命名空间划分

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1263]
- [x] - 生成新的国际化格式
- [x] - 支持新国际化文件加载
- [x] - 对接新旧格式
- [x] - 新旧格式转换
- [ ] - 按命名空间划分
- [ ] - 支持在页面编辑国际化内容

```
accounts.zh-CN.objectTranslation.yml
=======

name: accounts
label: 客户
description: 客户信息
fields:
  name:
    label: 名称
    description: 
  phone: 
    label: 电话
    help: 
    desciption: 
listviews:
  all:
    label: 所有
actions:
  done:
    label: 
customlabels:
```
