### ISSUE TITLE
.object.yml 新增属性 i18n，用于处理对象国际化

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#145]
定义格式 
```yml
  name:
    label: Name
    i18n:
      en: Name
      zh-CN: 姓名
```

objects 在传送到 creator 前台时，根据用户语言自动用 i18n 下的内容替换掉 label
