### ISSUE TITLE
object_layouts 对象改造

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#1484]
数据结构如下：
```
name: default
label: Community Layout
object: community
buttons: 
  - button_name:
    visible_on: 
compact_layout_fields: []
fields: 
  - field_name: name
    is_wide: false
    readonly: true
    required: true
    group: General
    visible_on: "this.name.length === 0"
related_lists: 
  - object_name: community_pages
    sort_field: created
    sort_order: desc
    field_name:
      - field
      - created
    visible_on: 
profiles:
template: 

```
