### ISSUE TITLE
支持xxx.action.js

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#264]
-----定义对象action.js

xxx.action.js
```
module.exports = {
    updateOrgs: function(){
        console.log('updateOrgs');
    },

    updateOrgsVisible: function(){
        console.log('updateOrgsVisible');
    }
}
```

-----定义对象.yml
xxx.object.yml:

```
actions:
    updateOrgs:
        label:
        on:
        visible: false
```

=====程序处理之后的yml结构=====
```
actions:
    updateOrgs:
        label:
        on:
        visible: function(){
            console.log('updateOrgsVisible');
        }
        todo: function(){
            console.log('updateOrgs');
        }
```
