### ISSUE TITLE
支持在界面定义新对象，字段

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#271]
- [x] 公有云不开放: 如果配置文件中tenant.saas 为true,则不从数据库中加载自定义对象

- [x] 自定义对象，字段都以__c结尾；
- [x] 自定义对象、字段的名称限制：只能包含字母数字字符，必须以字母开头，不能以下划线字符结尾或包含两个连续的下划线字符

- [x] 自定义对象根据space显示
- [x] 自定义对象权限根据space计算

在项目的src文件夹下添加文件：object_manager.app.yml， 内容为：
```yml
_id: object_manager
name: 对象管理
is_creator: false
admin_menus:
  - _id: object_manager
    name: 对象管理
    permission_sets:
      - admin
    object_name: objects
    parent: menu_advanced
    sort: 1
```
