### ISSUE TITLE
按向导配置email未生效

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#306]
steedos_config配置email
![image](https://user-images.githubusercontent.com/7553007/81463526-c0223c80-91ec-11ea-9234-2dc7e3cc419d.png)
遇到发邮件，会报错
![image](https://user-images.githubusercontent.com/7553007/81463553-ddefa180-91ec-11ea-8416-3b182e96c01d.png)

**Comment by yinlianghui** [comment]
steedos.config.yml中配置方法：
```
email:
  url: ${MAIL_URL}
  from: ${MAIL_FROM}
  secure: true
```
或
```
email:
  host: ${MAIL_HOST}
  port: 465
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  from: ${MAIL_FROM}
  secure: true
```
> 以下两种都配置方法都可以，如果同时配置了url入用户名密码，则优先使用url
