### ISSUE TITLE
很多内置对象以及低代码开发的对象复制视图功能中显示的列没有复制过来

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3308]
- 准确的说columns属性是以下第一种对象数组的格式是正常的，第二种字符串数组是坏的。
- 可视化界面上创建的自定义对象上是好的。
- apps项目中也有很多对象是字符串数组格式也是坏的

```
list_views:
  recent:
    label: 最近查看
    columns:
      - field: name
        width: 300
        wrap: true
```

```
list_views:
  recent:
    label: 最近查看
    columns:
      -  name
```
<img width="331" alt="image" src="https://user-images.githubusercontent.com/6219465/169491773-6d79e8af-4093-45e7-9902-4df91340ae91.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/6219465/169493099-ea217800-4a2e-4bf5-9b7f-523af92610b7.png">
