### ISSUE TITLE
space_users添加profile属性

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#338]
```
space_users:
  fields:
    profile:
      required: false
      type: select
      options: admin,user,supplier,customer
```
