### ISSUE TITLE
jwt 参数与返回结果调整

### ISSUE THREAD

**Issue by baozhoutao** [steedos/steedos-platform#3536]
jwt 相关参数调整到 
```
tenant:
  tokenSecret:
  accessTokenExpiresIn:  默认值 90d
  refreshTokenExpiresIn: 默认值 7d
```

接口返回的accessToken应包含 name、email、userId
