### ISSUE TITLE
base.object.yml 基础对象支持国际化

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3690]
目前有一个值为“系统信息”的group需要翻译：
```
  modified:
    label: Modification Time
    type: datetime
    readonly: true
    sortable: true
    index: true
    group: 系统信息
    sort_no: 9999
```
