### ISSUE TITLE
VSCODE的菜单steedos:Create i18N给应用执行国际化时添加admin_menus相关翻译key

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3695]
<img width="841" alt="image" src="https://user-images.githubusercontent.com/6219465/181027066-0025ac70-2e24-424f-96c0-a07236aa141d.png">

国际化后的文件内容如：
```
CustomApplications:
  apps_pages:
    name: Apps
    description: null
```
