### ISSUE TITLE
页面布局配置文件中name为default时，未加载

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#3764]
如：`stock_in.default.layout.yml`
```yml
name: default
buttons:
  - button_name: standard_new
  - button_name: standard_edit
  - button_name: standard_delete
fields:
  - field_name: stock_number
    is_readonly: true
    is_required: false
```
