### ISSUE TITLE
元数据加载的时候应该转换下type类型的字段的options属性，支持配置为Label1:field1,Label2:field2这种一行简写模式

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#3894]
```
  type:
    label: Type
    type: select
    firstOption: false
    options: Profile:profile,Permission set:permission_set
    defaultValue: permission_set
```
