### ISSUE TITLE
lookup字段，同时设置了multiple和defaultValue，且不是必填时，新建记录时清除字段值保存会报错

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#396]
![image](https://user-images.githubusercontent.com/6219465/84984210-f8625680-b16c-11ea-9aab-a39dd4520b59.png)

```
  assignees:
    label: Assignees
    type: lookup
    reference_to: users
    defaultValue: "[{userId}]"
    multiple: true
    name: assignees
    filterable: true
```
