### ISSUE TITLE
对象中如果未配置user权限组的权限，普通用户应该不能访问

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#418]
用户反馈 .object.yml 下的 permission_set 只配置了admin, 没有配置 user，但是 user可以访问。

```
permission_set: 
  admin:
    allowRead: true
    ...
```
