### ISSUE TITLE
[Feature]: 审批列表，应支持按紧急程度显示红/蓝/紫色等颜色样式

### ISSUE THREAD

**Issue by marchtian** [steedos/steedos-platform#4924]
### Description

![image](https://user-images.githubusercontent.com/7553007/236979193-7961b5e4-ddd7-41f0-a702-dcf97dbb59f7.png)

### Steps To Reproduce 重现步骤

审批，列表页

### Version 版本

2.5.0-beta.21

**Comment by marchtian** [comment]
根据表单中的priority的值，文件标题显示不同的颜色
- [ ] 红色：特急
- [ ] 紫色：紧急
- [ ] 蓝色：办文
- [ ] 黑色（默认）：普通

**Comment by hotlong** [comment]
@baozhoutao 考虑一下如何实现。

**Comment by baozhoutao** [comment]
1 instances、instances_tasks 新增字段: extras
2 extras 的值根据表单字段上配置的 运行列表显示 的定义来自动从values中获取维护

3 列表视图配置额外查询字段 
```
extra_columns:
  - extras
```

4 配置name字段样式
```
    amis:
      className:
        'color-priority-danger': "${extras && extras.priority == '特急'}"
        'color-priority-warning': "${extras && extras.priority == '紧急'}"
        'color-priority-muted': "${extras && extras.priority == '办文'}" 
```
