### ISSUE TITLE
[Bug]: apps extend数组属性时有问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5146]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6219465/976bc0cf-1cfc-4176-82d9-daae520bacd9)

![image](https://github.com/steedos/steedos-platform/assets/6219465/de7fe45b-9f94-4328-a4d2-488f051610d1)

### Steps To Reproduce 重现步骤

1. 在模板项目中新建cms.app.yml文件，extend内核中的cms应用属性，内容大致如下：
```
code: cms
name: 信息发布224
extend: cms
is_creator: true
mobile: true
objects: [] //重点是这个数组属性设置为空，但是没有生效
sort: 9100
tab_items:
  object_cms_sites:
    index: 1
  object_cms_categories:
    index: 2
  object_cms_posts:
    index: 3
tabs:
  - object_cms_sites
  - object_cms_categories
  - object_cms_posts
visible: true
```
3. 重启服务后看到cms应用中出现了两份选项卡，因为objects属性未能成功重写为空数组
4. 因为不加extend: cms这行的话，cms应用都不会出现在应用程序启动器中，所以extend其他属性肯定是生效的，只有objects属性未能成功重写

### Version 版本

2.5.x
