### ISSUE TITLE
[Bug]: 左侧菜单未能按照设置的分组顺序显示

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5314]
### Description

设置模块配置的分组中，高级设置在最后，但是却显示到中间。
```
tab_groups:
  - group_name: personal_settings
  - group_name: company_settings
  - group_name: apps
  - group_name: object_settings
  - group_name: user_interface
  - group_name: statistical_analysis
  - group_name: development
  - group_name: process_automation
  - group_name: approval_workflow
  - group_name: advanced_settings
```

### Steps To Reproduce 重现步骤

如上

### Version 版本

2.5.x
