### ISSUE TITLE
[Bug]: 选项卡url中配置了公式时，应用启动器打开异常

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5392]
### Description

<img width="1401" alt="企业微信截图_c6bc4c6b-5cc0-479d-91ce-a7387b042296" src="https://github.com/steedos/steedos-platform/assets/50353452/b4567628-3635-48eb-9939-53d8c0047b82">

```
name: admin_space_info
desktop: true
icon: account
is_new_window: false
label: 公司
mobile: true
permissions:
  - permission: 'on'
    permission_set: admin
  - permission: 'off'
    permission_set: user
  - permission: 'off'
    permission_set: customer
  - permission: 'off'
    permission_set: supplier
  - permission: 'off'
    permission_set: organization_admin
  - permission: 'off'
    permission_set: workflow_admin
type: url
url: /app/admin/spaces/view/${global.user.spaceId}
```

### Steps To Reproduce 重现步骤

1. 启动项目模版
2. 点击应用启动器
3. 点击公司

### Version 版本

2.5.13
