### ISSUE TITLE
[Bug]: 软件包中扩展设置菜单，点击菜单中自定义的选项卡未显示微页面

### ISSUE THREAD

**Issue by sunhaolin** [steedos/steedos-platform#5471]
### Description

![image](https://github.com/steedos/steedos-platform/assets/6194896/bbd4780a-d0e6-4b4d-97d8-22db38c3a64b)

admin.app.yml中添加新的tab_items指向自定义的应用程序微页面
点击菜单中的选项卡，微页面未显示

### Steps To Reproduce 重现步骤

1. 新建 应用程序 微页面 admin_pm_card
2. 新建 选项卡 admin_pm_card
3. admin.app.yml中配置
```yml
code: admin
name: admin_pm
tab_items:
  admin_pm_card:
    group: app_settings
    index: 50
```
    

### Version 版本

2.5.13-beta.22
