### ISSUE TITLE
[Feature]: 软件包识别 steedos.package.yml 作为当前软件包的元数据

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-platform#5475]
### Summary 摘要

```yml
name: @steedos/project-ee
label: 项目管理
description: 华炎魔方项目管理系统，是一套以项目为中心的融合数字化解决方案。以项目全生命周期管理为基础，通过BPM引擎推动项目全过程的规范与高效管理。有机融合了销售、合同、财务、费控等管理，留存全面、完整的业财数据资产。提供AI智能统计、分析项目业绩与发展趋势，助力项目驱动型企业的数字化转型。
icon: contract
dependencies:
  - @steedos/master
isPackage: true
```

内容和 package.service.js 中的 metadata.$package 合并,
- path 自动获取 package.service.yml 对应的文件夹 ？ 
- version 自动从 package.json 获取？

```js
metadata: {
        $package: {
            name: project.name,
            version: project.version,
            path: __dirname,
            isPackage: true
      }
}
```

### Why should this be worked on? 此需求的应用场景？

软件包定义
