### ISSUE TITLE
[Bug]: 通过amis设置defaultValue时报错

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#5521]
### Description

字段设置：
```yml
name: description
type: textarea
label: 描述
sort_no: 320
defaultValue: "${_master.record.description || ''}"
```
此时数据域中有description字段的值，值为null，点击保存报错：
Catch an error "Syntax error." while eval formula "${_master.record.description || ''}" with paramsfalse "{}" for "undefined"
description字段有值时，保存正常。
<img width="406" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/db623b62-5d7b-4c8b-9663-676215ef9f78">
<img width="1142" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/6aa2c52b-4664-44e2-a07b-95f02e4c8943">

### Steps To Reproduce 重现步骤

1、设置a、b两个对象，a为主表对象，b为子表对象，将b对象显示在a对象相关选项中。
2、a对象添加一个字段，新建一条a对象记录，不填写该字段值，b对象字段中defaultValue参考上面的yml文件
3、在a对象相关选项中新建b即可重现。

### Version 版本

2.5.15-beta.2
