### ISSUE TITLE
[Feature]: 复制记录时，会同时复制 owner, company_id 等字段，有时又不希望复制这些字段的值。

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5849]
### Summary 摘要

配置了默认值且visible_on为false的字段，在列表上使用复制新建功能时如何把字段值设置为默认值而不是被复制记录中的字段值
- 比如base.object.yml中的以下几个字段：

```yml
  owner:
    label: Owner
    type: lookup
    reference_to: users
    sortable: true
    index: true
    defaultValue: "{userId}"
    visible_on: "{{false}}"
    sort_no: 1000
  company_id:
    label: Division
    type: lookup
    reference_to: company
    sortable: true
    index: true
    defaultValue: !!js/function |
      function(){
        return Steedos.StandardObjects.Base.Fields.companyId.defaultValue.apply(this, arguments)
      }
    filtersFunction: !<tag:yaml.org,2002:js/function> |-
      function(filters, values){
        ...
      }
    visible_on: "{{false}}"
    sort_no: 1200

  company_ids:
       ....
```
以上字段在列表上新建复制记录时，界面上无法修改字段值，直接从列表中选中记录中复制原字段值不适合，需求应该是让这些字段值的默认值生效。
- base中的以下固定字段已经在前端发送适配器中写死始终不提交到服务端了所以不会有此问题：`instances、instance_state、created、created_by、modified、modified_by`
- 另外visible_on中是表达式，不一定是固定的`{{false}}`，如何考虑？

#### 备注：

`instances、instance_state`这两个字段因为始终不会让在前端放开修改，所以直接提交时写死不提交这些字段值就行，这种字段不存在上面的问题。

#### 可能的解决方案：

字段上加一个新的开关属性，当配置了此属性后，复制新建时不要把此字段值复制到新建记录表单中？而且让它的默认值生效。

### Why should this be worked on? 此需求的应用场景？

复制新建功能潜在问题
