### ISSUE TITLE
[Feature]: 增加字段类型table，使用steedos-input-table组件渲染，以改进原grid字段类型的编辑及只读效果

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#5870]
### Summary 摘要

比如把以下字段字段中的grid类型换成table就能使用steedos-input-table组件渲染该字段的编辑和只读效果。
另外支持为table类型字段配置columns属性（字符串数组或对象数组）用来描述显示哪些字段。
```yml
  options:
    type: grid # 换为table
    label: Options
    is_wide: true
    inlineHelpText: The label and value of each option cannot be empty. Set the background color to FFFFFF in hexadecimal format.
    visible_on: "{{formData.type === 'select' ? true: false}}"
    required: "{{formData.type === 'select' ? true: false}}"
    sort_no: 280
    amis:
      disabledOn: "${is_system == true}"
    # columns: ["label", "value"] 表示表格列中只显示这些字段，其他字段隐藏
  options.$:
    label: Options
    blackbox: true
    type: object
  options.$.label:
    label: Label
    type: text
    required: true
  options.$.value:
    label: Value
    type: text
    required: true
  options.$.color:
    label: Color
    type: text
    required: false
  options.$.description:
    label: Description
    type: text
    required: false
```

### Why should this be worked on? 此需求的应用场景？

优化grid字段编辑和只读效果
