### ISSUE TITLE
[Bug]:通过字段布局调整样式之后，同步成源代码，再deploy到数据库，报字段未填写:options

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#5985]
### Description

1、没点字段布局的对象，deploy是可以的
2、点击过字段布局，保存之后，同步成源代码，再deploy报错
3、报错信息
![image](https://github.com/steedos/steedos-platform/assets/129827462/c35558c8-b7b3-4c44-80cf-d9f75815af00)

platform源码地址： packages/metadata-api/src/metadata/collection/field.ts
![图片已粘贴至2023-12-18 14-17](https://github.com/steedos/steedos-platform/assets/129827462/c320c88d-1372-41b1-9a64-b18fa5019b76)

### Steps To Reproduce 重现步骤

1、通过字段布局调整样式，同步成源代码
2、再将该对象deploy到数据库
3、报错字段未填写:options

### Version 版本

 2.6.2-beta.14

**Comment by sunhaolin** [comment]
```yml
name: instance_state
label: 申请单审批状态
sort_no: 430
type: select
visible_on: '{{false}}'
```
select 字段类型未填写options属性，理应提示。
