### ISSUE TITLE
[Feature]: 子表组件增加开关属性控制弹出表单窗口是否显示新增和复制按钮

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6011]
### Summary 摘要

默认显示这两个按钮，增加属性脚本属性`buttonSaveAndNewVisibleOn`，``buttonSaveAndCopyVisibleOn``来控制这两个按钮的显隐规则。

![image](https://github.com/steedos/steedos-platform/assets/6219465/bc597349-1910-40c9-9d74-cd45d23b620c)

### Why should this be worked on? 此需求的应用场景？

子表组件优化

**Comment by yinlianghui** [comment]
方案换成支持重写整个dialog，比如在字段设置yml文件中改写成以下配置，可以实现弹出窗口只有一个完成按钮，且弹出窗口标题改为“时间触发器行明细”：
```yml
  time_triggers:
    type: table
    label: 时间触发器
    is_wide: true
    required: false
    group: time_dependent_action
    amis:
      columns: ["number", "unit", "type", "date_field"]
      dialog: {
        "actions": [
            {
                "type": "button",
                "label": "完成",
                "actionType": "confirm",
                "level": "primary"
            },
        ]
      }
```
