### ISSUE TITLE
[Feature]: 编辑列表视图时，支持配置列表视图权限，例如共享给指定部门

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6150]
### Summary 摘要

目前只能通过权限集配置禁用的列表视图，但是权限集只能绑定到人员，不能绑定到部门。

![image](https://github.com/steedos/steedos-platform/assets/6219465/d55d9ff0-f2f1-4461-b8a1-5e9c9ebbd779)

### Why should this be worked on? 此需求的应用场景？

项目中遇到需要按部门设置隐藏all视图查看权限的需求。

**Comment by hotlong** [comment]
<img width="659" alt="企业微信截图_b40f4442-b816-4454-ba98-8995479e3a60" src="https://github.com/steedos/steedos-platform/assets/50353452/39729be4-6180-4941-bc87-07440749b632">

**Comment by yinlianghui** [comment]
开发方案：
- 列表视图对象上增加两个字段，并把界面上“共享视图到工作区”字段隐藏，用增加的两个字段代替，界面效果做成上面截图所示的salefore风格效果。
```
  shared_to:
    label: 谁可以查看此列表视图？
    type: select
    defaultValue: space
    required: true
    options:
      - label: 只有我可以查看此列表视区
        value: mine
      - label: 所有用户均可以查看此列表视图
        value: space
      - label: 与组织共享列表视图
        value: organizations 
  shared_to_organizations:
    label: 共享列表视图给哪些组织？
    type: lookup
    reference_to: organizations
    multiple: true
    # shared_to为organizations时才显示此字段
    depend_on:
      - shared_to
```
- 原“共享视图到工作区”字段，即shared字段虽然在界面上隐藏了，但是其功能保留，包括服务端触发器中非管理员强制把shared改为false等逻辑
- 新加的shared_to属性不设置默认值，该值为空时保持原shared字段的共享规则
- 界面上用户把shared_to设置为mine/organizations时，同时把shared字段值设置为false（服务端触发器）
- 界面上用户把shared_to设置为space时，同时把shared字段值设置为true（服务端触发器）
- 对象的uiSchema接口之前返回的有权限查看的视图规则变更：
  - 原来相关规则：`[['owner', '=', userSession.userId], 'or', ['shared', '=', true]] `
  - 改为后面追加规则： or shared_to 等于 space or (shared_to 等于 organizations 并且 shared_to_organizations包括userSession.organizations_parents)
