### ISSUE TITLE
[Bug]: 记录详情页，鼠标移入人员字段后报错：无法找到记录

### ISSUE THREAD

**Issue by sujiahao66** [steedos/steedos-platform#6413]
### Description

在记录详情页鼠标移入“申请人”字段后，报错“无法找到记录”。
同一条记录下，鼠标移入创建人字段未出现此问题（图二）。
申请人字段设置如下
```yaml
name: applicant__c
label: 申请人
reference_to: space_users
reference_to_field: user
sort_no: 110
type: lookup

```
<img width="1431" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/f7e6c3a9-c06a-4d7c-8dad-c32d9fc9ddc6">
<img width="1275" alt="image" src="https://github.com/steedos/steedos-platform/assets/126655403/3e0b9bc5-970e-4b7f-bb86-d2ce71886f8c">

### Steps To Reproduce 重现步骤

无法确认具体重现规则

### Version 版本

2.6.7-beta.5
