### ISSUE TITLE
[Bug]: 下拉框字段上配置amis.type=radios时，只读界面该字段值显示为空值了

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#6433]
### Description

且空值显示为“请选择”了
![image](https://github.com/steedos/steedos-platform/assets/6219465/04662a9f-66c0-4cb0-a8cd-e831c2d884bc)

```
  shared_to:
    label: Who can see this list view?
    type: select
    defaultValue: mine
    options:
      - label: Only I can view this list view.
        value: mine
      - label: This list view is available to all users.
        value: space
      - label: Share the list view with some organizations.
        value: organizations 
    visible_on: "${global.user.is_space_admin}"
    group: share_rules
    amis:
      type: radios
      inline: false
```

### Steps To Reproduce 重现步骤

如题

### Version 版本

2.6.7.beta.x
