### ISSUE TITLE
[Bug]: autoFill填充的目标字段为lookup和组织机构时，填充之后，有时候显示id（amis已经修正）

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6601]
### Description

![image](https://github.com/steedos/steedos-platform/assets/129827462/74efcdcf-a14f-4d3b-9457-6fb2672bd297)

### Steps To Reproduce 重现步骤

yml代码
```
name: user
auto_fill_mapping:
  - from: mobile
    to: phone
  - from: organization
    to: department
create: true
defaultValue: '{{global.userId}}'
filterable: false
generated: false
group: 提单信息
hidden: false
index: false
is_name: false
is_wide: false
label: 提单人
multiple: false
primary: false
readonly: false
reference_to: space_users
reference_to_field: user
required: true
searchable: false
show_as_qr: false
sort_no: 200
sortable: false
type: lookup
unique: false
write_requires_master_read: false
```

### Version 版本

 2.7.0-beta.6
