### ISSUE TITLE
[Bug]: 主表上两个汇总字段汇总子表上同一个字段，编辑子表时，主表触发器会触发两次

### ISSUE THREAD

**Issue by ysc1234** [steedos/steedos-platform#6645]
主表上的两个汇总字段汇总同一个子表上的同一个字段，编辑该子表的那个被汇总字段，主表的update触发器会触发两次

### Description

1、主表上的两个汇总字段
```
name: amount_stocking
create: true
data_type: number
enable_thousands: true
filterable: false
generated: false
group: 库存信息
hidden: false
index: false
is_name: false
is_wide: false
label: 待入库数量
multiple: false
precision: 18
primary: false
readonly: false
scale: 2
searchable: false
show_as_qr: false
sort_no: 460
sortable: false
static: false
summary_field: amount_actual
summary_filters:
  - field: state
    operation: <>
    value: audited
summary_object: device_inbound_details
summary_type: sum
type: summary
unique: false
write_requires_master_read: false
```

```
name: amount_stocking
create: true
data_type: number
enable_thousands: true
filterable: false
generated: false
group: 库存信息
hidden: false
index: false
is_name: false
is_wide: false
label: 待入库数量
multiple: false
precision: 18
primary: false
readonly: false
scale: 2
searchable: false
show_as_qr: false
sort_no: 460
sortable: false
static: false
summary_field: amount_actual
summary_filters:
  - field: state
    operation: <>
    value: audited
summary_object: device_inbound_details
summary_type: sum
type: summary
unique: false
write_requires_master_read: false
```

### Steps To Reproduce 重现步骤

如标题

### Version 版本

2.7.0-beta.11
