### ISSUE TITLE
日期控件当有默认值时，应该也强制保存为utc的0点

### ISSUE THREAD

**Issue by yinlianghui** [steedos/steedos-platform#665]
```
  test_due_date1:
    label: Test Due Date1
    type: date
    sortable: true
    defaultValue: "{now}"
  test_due_date2:
    label: Test Due Date2
    type: date
    sortable: true
    defaultValue: !<tag:yaml.org,2002:js/function> |-
      function () {
        return new Date()
            }
```
即以上两种方式字段的默认值应该保存成当天utc的0点
